### ISSUE TITLE
Running Inferelator without Metadata or TFs

### ISSUE THREAD

**Issue by rlittman16** [flatironinstitute/inferelator#17]
Hello,

I am trying to run the Inferelator pipeline on single cell expression data. It seems that it requires metadata on each cell such as in yeast_microarray_meta_data.tsv. We don't have this kind of data for our cells. Would it be possible to run without the meta data file? 

Additionally is it possible to run this for cell types without well defined transcription factors as priors.

Thanks in advanced!

**Comment by asistradition** [comment]
Sorry for the delay in responding.

You can set the workflow `meta_data_file` parameter to None (something like `wkf.meta_data_file = None` in the run script) and it'll ignore metadata (really it'll just make a mock metadata assuming that everything is in one group and there is no time information).

The performance without priors is... generally quite a bit weaker. I would suggest that if you do so that you run at least one shuffled negative control to establish a baseline. You can turn off the inclusion of prior information by adding the following two lines to the run script:

    from inferelator.preprocessing.tfa import NoTFA
    worker.tfa_driver = NoTFA

You'll still need to make a prior matrix (genes x tfs) that's all 0s; the next release will handle generating mock files for you, but that build isn't entirely stable just yet.

**Comment by asistradition** [comment]
Forgot to update this:

The workflow will generate a null prior now if no prior file is provided and the following argument is provided: `worker.set_network_data_flags(use_no_prior=True)`

The transcription factor activity calculation can be skipped (using expression data instead of TFA) with the following argument: `worker.set_tfa(tfa_driver=False)`
